# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host:     localhost
  username: postgres
  password: 123456
  port:     5432
  pool:     5
  timeout: 5000
  reaping_frequency: 10

development:
  <<: *default
  database: fitstyle3_db_development

production: &production
  <<: *default
  database: fitstyle3_db_production


test:
  <<: *default
  database: fitstyle3_db_test